services:
  empresta:
    build: .
    image: empresta:latest
    container_name: empresta
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - empresta-network
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html
  mariadb:
    image: mariadb:11
    container_name: empresta_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: empresta
      MYSQL_USER: empresta
      MYSQL_PASSWORD: empresta
      MYSQL_ROOT_PASSWORD: empresta
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - empresta-network

  selenium:
    image: selenium/standalone-chrome
    container_name: empresta_selenium
    ports:
      - "7900:7900" # VNC (pra ver o browser rodando)
    networks:
      - empresta-network
    shm_size: 2gb

networks:
  empresta-network:

volumes:
  mariadb_data:

